### PR TITLE
provide operator apis in separate module with less dependencies

### PR DESCRIPTION
**Pull request by hensur**
Using a separate package for the exported apis allows other go modules to import this operator's k8s APIs without indirectly importing all dependencies in the main `go.mod`.

This change also moves some methods which were defined for api types from the api package to the `controllers/helper` package. The previous receivers are now parameters of the methods.

Code Generation fixed. Instead of putting a go.mod into the api folder, the generate Target will now copy generated apis into a new `apipkg` package, which has a static go.mod. This package can then be imported by other go modules.

### CODE REVIEW

**Review by martin-helmich — APPROVED** [review]

**Comment by dkorittki** [comment]
Naming suggestion for the new api module: `github.com/mittwald/harbor-operator/resources` rather than `github.com/mittwald/harbor-operator/apipkg`. Because calling a module path `pkg` does not sound right to me. Best name to me would be `github.com/mittwald/harbor-operator/api` but operator-sdk doesn't like that, right?

**Comment by martin-helmich** [comment]
>Best name to me would be github.com/mittwald/harbor-operator/api but operator-sdk doesn't like that, right?

This will bite us when upgrading to Operator SDK 1.0 (see #52), in which `/api` seems to be the default expected path for API types. `/resources` sounds good, but OTOH, having both `/api` AND `/resources` might also be massively confusing... 🤔

**Comment by dkorittki** [comment]
> > Best name to me would be github.com/mittwald/harbor-operator/api but operator-sdk doesn't like that, right?
> 
> This will bite us when upgrading to Operator SDK 1.0 (see #52), in which `/api` seems to be the default expected path for API types. `/resources` sounds good, but OTOH, having both `/api` AND `/resources` might also be massively confusing... 🤔

Yeah, thats a bummer. Can't win in this situation I guess. I would leave merging to @elenz97 since it's his commit in which it will get merged.

**Comment by martin-helmich** [comment]
How about a package path that clearly and unambiguously suggests that it contains a *copy* of the API code? Like `export/api` or something similar?

**Comment by hensur** [comment]
We could also adhere to the [golang-standards](https://github.com/golang-standards/project-layout) project-layout, where exported library code lives in `pkg`. This would also ensure some backwards compatibility, as all operators < osdk v1 already provide their API definitions in `pkg/apis`.

**Comment by dkorittki** [comment]
> We could also adhere to the [golang-standards](https://github.com/golang-standards/project-layout) project-layout, where exported library code lives in `pkg`. This would also ensure some backwards compatibility, as all operators < osdk v1 already provide their API definitions in `pkg/apis`.

Sounds good to me 👍

**Comment by hensur** [comment]
Ok, I've moved the api exports from `apipkg` to `pkg/apis`.

**Review by martin-helmich — APPROVED** [review]

**Review by elenz97 — APPROVED** [review]

**Pull request merged**
